version: "3.8"

services:
  godot-server:
    image: ubuntu:latest # Use a base Linux image. Consider a smaller base like alpine if preferred.
    container_name: godot-server
    ports:
      - "8080:8080" # Replace with the port Godot will serve on. Add more ports if needed.
    volumes:
      - ./game:/usr/src/app # Mount your Godot project directory
    environment:
      DISPLAY: :99.0 # Use a virtual display, necessary for some Godot headless operations
    entrypoint: >
      sh -c "
      apt-get update &&
      apt-get install -y wget xvfb libgl1 &&
      wget https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip &&
      unzip Godot_v4.2.2-stable_linux.x86_64.zip -d /usr/local/bin &&
      chmod +x /usr/local/bin/Godot_v4.2.2-stable_linux.x86_64 &&
      xvfb-run -a /usr/local/bin/Godot_v4.2.2-stable_linux.x86_64 --main-pack /usr/src/app/game.pck --server --port 8080
      "
